In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])

print("Original array:", arr)
print("Reversed array:", arr[::-1])

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [ ]:
array1 = np.array([[1, 2, 3],
                   [2, 4, 5],
                   [1, 2, 3]])

print("Using flatten():")
print(array1.flatten())

print("Using ravel():")
print(array1.ravel())

Using flatten():
[1 2 3 2 4 5 1 2 3]
Using ravel():
[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print("Element-wise comparison:")
print(arr1 == arr2)

print("Are the arrays equal?")
print(np.array_equal(arr1, arr2))

Element-wise comparison:
[[ True  True]
 [ True  True]]
Are the arrays equal?
True


In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)

i = np.argmax(counts)
value = values[i]

print("Most frequent value:", value)
print("Frequency:", counts[i])
print("Indices:", np.where(x == value)[0])

Most frequent value: 1
Frequency: 5
Indices: [0 5 7 8 9]


In [ ]:
y = np.array([1,1,1,2,3,4,2,4,3,3])

values, counts = np.unique(y, return_counts=True)

i = np.argmax(counts)
value = values[i]

print("Most frequent value:", value)
print("Frequency:", counts[i])
print("Indices:", np.where(y == value)[0])

Most frequent value: 1
Frequency: 3
Indices: [0 1 2]


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

print("Matrix:")
print(gfg)

print("Sum of all elements:", np.sum(gfg))
print("Row-wise sum:", np.sum(gfg, axis=1))
print("Column-wise sum:", np.sum(gfg, axis=0))

Matrix:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [ ]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

print("Matrix:")
print(n_array)

print("\nSum of diagonal elements:")
print(np.trace(n_array))

eigenvalues, eigenvectors = np.linalg.eig(n_array)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

print("\nInverse:")
print(np.linalg.inv(n_array))

print("\nDeterminant:")
print(np.linalg.det(n_array))

Matrix:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Sum of diagonal elements:
176

Eigenvalues:
[98.16835147 28.097044   49.73460452]

Eigenvectors:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

Inverse:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinant:
137180.0000000001


In [ ]:
p = np.array([[1, 2],
              [2, 3]])

q = np.array([[4, 5],
              [6, 7]])

print("Matrix multiplication:")
print(np.matmul(p, q))

print("\nCovariance:")
print(np.cov(p.flatten(), q.flatten()))

Matrix multiplication:
[[16 19]
 [26 31]]

Covariance:
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [ ]:
p = np.array([[1, 2],
              [2, 3],
              [4, 5]])

q = np.array([[4, 5, 1],
              [6, 7, 2]])

print("Matrix multiplication:")
print(np.matmul(p, q))

print("\nCovariance:")
print(np.cov(p.flatten(), q.flatten()))

Matrix multiplication:
[[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
x = np.array([[2, 3, 4],
              [3, 2, 9]])

y = np.array([[1, 5, 0],
              [5, 10, 3]])

print("Inner product:")
print(np.inner(x, y))

print("\nOuter product:")
print(np.outer(x, y))

print("\nCartesian product:")
print(np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2))

Inner product:
[[17 52]
 [13 62]]

Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])

print("Array:")
print(array)

Array:
[[ 1 -2  3]
 [-4  5 -6]]


In [ ]:
print("Absolute value:")
print(np.abs(array))

Absolute value:
[[1 2 3]
 [4 5 6]]


In [ ]:
print("Flattened array percentiles:")
print(np.percentile(array, [25, 50, 75]))

Flattened array percentiles:
[-3.5 -0.5  2.5]


In [ ]:
print("Column-wise percentiles:")
print(np.percentile(array, [25, 50, 75], axis=0))

Column-wise percentiles:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


In [ ]:
print("Row-wise percentiles:")
print(np.percentile(array, [25, 50, 75], axis=1))

Row-wise percentiles:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
print("Flattened array:")

print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard deviation:", np.std(array))

Flattened array:
Mean: -0.5
Median: -0.5
Standard deviation: 3.8622100754188224


In [ ]:
print("Column-wise:")

print("Mean:", np.mean(array, axis=0))
print("Median:", np.median(array, axis=0))
print("Standard deviation:", np.std(array, axis=0))

Column-wise:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard deviation: [2.5 3.5 4.5]


In [ ]:
print("Row-wise:")

print("Mean:", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Standard deviation:", np.std(array, axis=1))

Row-wise:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard deviation: [2.05480467 4.78423336]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Original array:")
print(a)

Original array:
[-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]


In [ ]:
print("Floor:")
print(np.floor(a))

Floor:
[-2. -2. -1.  0.  1.  1.  3.]


In [ ]:
print("Ceiling:")
print(np.ceil(a))

Ceiling:
[-1. -1. -0.  1.  2.  2.  3.]


In [ ]:
print("Truncated:")
print(np.trunc(a))

Truncated:
[-1. -1. -0.  0.  1.  1.  3.]


In [ ]:
print("Rounded:")
print(np.round(a))

Rounded:
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
!pip install pillow

In [ ]:
from PIL import Image
import numpy as np

In [ ]:
def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)

    if len(arr.shape) == 2:
        np.savetxt("image_gray.txt", arr, fmt="%d")
        print("Grayscale image saved as image_gray.txt")
    else:
        np.savetxt("image_rgb.txt", arr.reshape(arr.shape[0], -1), fmt="%d")
        print("RGB image saved as image_rgb.txt")

    return arr

In [ ]:
arr = img_to_array("20221230_160548.jpg")

RGB image saved as image_rgb.txt


In [ ]:
print("Shape:", arr.shape)

Shape: (3000, 4000, 3)


In [ ]:
data = np.loadtxt("image_rgb.txt", dtype=int)

print("Loaded data:")
print(data)

print("Shape:", data.shape)

Loaded data:
[[156 155 161 ... 203 207 206]
 [159 158 164 ... 196 200 199]
 [164 163 169 ... 185 189 188]
 ...
 [  5   5   5 ... 150 127 111]
 [  5   5   5 ... 149 128 111]
 [  5   5   5 ... 149 128 111]]
Shape: (3000, 12000)
